#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

#  jekyll serve --config _config.yml,_config_dev.yml

url: 		'http://localhost:4000'
baseurl: 	''

ignore:
   - _jekyll-themes
   - thank-you
   - data
   - about
   - redirect
   - svg
   - font-awesome
sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  # line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  # sourcemap: true

# compress_html: false

# Disable when not in production
analytics: 'no'
ad: 'no'
disqus: 'no'
sumo: 'no'
limit: 'yes'